Repository openshift/managed-release-bundle-osd, pull requests merged in 2024-06, with the labels that each got.

#28 misc: update readme
  README.md
Labels: approved, lgtm

#35 4.12 bundle should cover ocp 4.5 to 4.12
  hack/sss.yaml
Labels: approved, lgtm

#37 hack: look up digest for latest registry image
  hack/update-operator-release.sh
Labels: approved, lgtm

#38 hack: look up digest for latest registry image
  hack/update-operator-release.sh
Labels: approved, lgtm

#43 update curl stuff
  hack/update-operator-release.sh
Labels: do-not-merge/hold, approved

#49 Operator updater updates
  hack/update-operator-release.sh
Labels: approved, lgtm

#55 mv resources file
  resources/osd-example-operator/resources.yaml.gotmpl
Labels: approved, lgtm

#57 Fix templating for operator and add namespaces phase
  hack/update-operator-release.sh
  resources/manifest.yaml
Labels: approved

#69 Missed minor file syncs
  hack/package-bundle.sh
  hack/update-operator-release.sh
Labels: approved

#73 Switch to app-iface-injected MAJOR_MINOR
  hack/sss.yaml
Labels: do-not-merge/hold, approved

#77 Switch to app-iface-injected MAJOR_MINOR
  hack/sss.yaml
Labels: approved

#78 Switch to app-iface-injected MAJOR_MINOR
  hack/sss.yaml
Labels: approved

#79 Switch to app-iface-injected MAJOR_MINOR
  hack/sss.yaml
Labels: approved
